//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphicalUserInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphicalUserInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20945597 {
            get {
                object obj = ResourceManager.GetObject("20945597", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _307ce493_b254_4b2d_8ba4_d12c080d6651 {
            get {
                object obj = ResourceManager.GetObject("307ce493-b254-4b2d-8ba4-d12c080d6651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4498897 {
            get {
                object obj = ResourceManager.GetObject("4498897", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled! Please contact us for support!.
        /// </summary>
        internal static string AccountDisabledErrorString {
            get {
                return ResourceManager.GetString("AccountDisabledErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avt {
            get {
                object obj = ResourceManager.GetObject("avt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg1 {
            get {
                object obj = ResourceManager.GetObject("bg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg2 {
            get {
                object obj = ResourceManager.GetObject("bg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to close your saving before its maturity day. You will benefit only non-term savings interest. Are you sure you want to proceed this?.
        /// </summary>
        internal static string ClosingSavingBeforeMaturityDayWarningString {
            get {
                return ResourceManager.GetString("ClosingSavingBeforeMaturityDayWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully closing your saving!.
        /// </summary>
        internal static string ClosingSavingSuccessfullyString {
            get {
                return ResourceManager.GetString("ClosingSavingSuccessfullyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComputerProcessImage {
            get {
                object obj = ResourceManager.GetObject("ComputerProcessImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong confirm password, Please retry!.
        /// </summary>
        internal static string ConfirmationPasswordNotMatchedString {
            get {
                return ResourceManager.GetString("ConfirmationPasswordNotMatchedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConfirmationTitleString {
            get {
                return ResourceManager.GetString("ConfirmationTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ #,##0.00##;-$ #,##0.00##.
        /// </summary>
        internal static string CurrencyStringFormat {
            get {
                return ResourceManager.GetString("CurrencyStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DateOnlyStringFormat {
            get {
                return ResourceManager.GetString("DateOnlyStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm:ss tt dd/MM/yyyy.
        /// </summary>
        internal static string DateTimeStringFormat {
            get {
                return ResourceManager.GetString("DateTimeStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposited successfully!.
        /// </summary>
        internal static string DepositSuccessfullyString {
            get {
                return ResourceManager.GetString("DepositSuccessfullyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email {
            get {
                object obj = ResourceManager.GetObject("email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content shall not be empty. Please type the content and try again..
        /// </summary>
        internal static string ErrorEmptyContentString {
            get {
                return ResourceManager.GetString("ErrorEmptyContentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitleString {
            get {
                return ResourceManager.GetString("ErrorTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit?.
        /// </summary>
        internal static string ExitConfirmationString {
            get {
                return ResourceManager.GetString("ExitConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expenses {
            get {
                object obj = ResourceManager.GetObject("expenses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export file!.
        /// </summary>
        internal static string ExportingFileFailedString {
            get {
                return ResourceManager.GetString("ExportingFileFailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file successfully!.
        /// </summary>
        internal static string ExportingFileSuccessfullyString {
            get {
                return ResourceManager.GetString("ExportingFileSuccessfullyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to loading your info! Please try again later!.
        /// </summary>
        internal static string FailedLoadingCustomerInfoString {
            get {
                return ResourceManager.GetString("FailedLoadingCustomerInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string FemaleString {
            get {
                return ResourceManager.GetString("FemaleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FrustratedHeadGifImage {
            get {
                object obj = ResourceManager.GetObject("FrustratedHeadGifImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpImage {
            get {
                object obj = ResourceManager.GetObject("HelpImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap How_to_Password_Protect_Antivirus_Settings__Kaspersky_Daily {
            get {
                object obj = ResourceManager.GetObject("How to Password Protect Antivirus Settings -Kaspersky Daily", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationTitleString {
            get {
                return ResourceManager.GetString("InformationTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #,0.00#%/year.
        /// </summary>
        internal static string InterestTextFormatString {
            get {
                return ResourceManager.GetString("InterestTextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid customer ID. Please check and try again..
        /// </summary>
        internal static string InvalidCustomerIdString {
            get {
                return ResourceManager.GetString("InvalidCustomerIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoginImage {
            get {
                object obj = ResourceManager.GetObject("LoginImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log out?.
        /// </summary>
        internal static string LogOutConfirmationString {
            get {
                return ResourceManager.GetString("LogOutConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOutString {
            get {
                return ResourceManager.GetString("LogOutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string MaleString {
            get {
                return ResourceManager.GetString("MaleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is invalid. Please try again..
        /// </summary>
        internal static string NewPasswordInvalidString {
            get {
                return ResourceManager.GetString("NewPasswordInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer is currently logged in!.
        /// </summary>
        internal static string NoCustomerLoggingInString {
            get {
                return ResourceManager.GetString("NoCustomerLoggingInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string NotificationTitleString {
            get {
                return ResourceManager.GetString("NotificationTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password cannot be left empty..
        /// </summary>
        internal static string OldPasswordEmptyString {
            get {
                return ResourceManager.GetString("OldPasswordEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is not correct. Please try again..
        /// </summary>
        internal static string OldPasswordIncorrectString {
            get {
                return ResourceManager.GetString("OldPasswordIncorrectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the following information of depositing saving before processing:
        ///- Periods (months): {0}
        ///- Annual interest rate: {1:#,0.00##%}/year
        ///- Deposit amount: {2:#,0.00##}.
        /// </summary>
        internal static string OpeningSavingConfirmationStringFormat {
            get {
                return ResourceManager.GetString("OpeningSavingConfirmationStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opening a saving!.
        /// </summary>
        internal static string OpeningSavingSuccessfullyString {
            get {
                return ResourceManager.GetString("OpeningSavingSuccessfullyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap otp {
            get {
                object obj = ResourceManager.GetObject("otp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap padlock {
            get {
                object obj = ResourceManager.GetObject("padlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PadlockImage {
            get {
                object obj = ResourceManager.GetObject("PadlockImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be blank!.
        /// </summary>
        internal static string PasswordBlankWarningString {
            get {
                return ResourceManager.GetString("PasswordBlankWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully!.
        /// </summary>
        internal static string PasswordChangingSuccessfullyString {
            get {
                return ResourceManager.GetString("PasswordChangingSuccessfullyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct! Please try again!.
        /// </summary>
        internal static string PasswordIncorrectWarningString {
            get {
                return ResourceManager.GetString("PasswordIncorrectWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saving {
            get {
                object obj = ResourceManager.GetObject("saving", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files (*.xlsx)|*.xlsx;*.xls.
        /// </summary>
        internal static string SavingExcelFileFilter {
            get {
                return ResourceManager.GetString("SavingExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap savings1 {
            get {
                object obj = ResourceManager.GetObject("savings1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap savingsImage {
            get {
                object obj = ResourceManager.GetObject("savingsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SavingsReport {
            get {
                object obj = ResourceManager.GetObject("SavingsReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap security_shield__1_ {
            get {
                object obj = ResourceManager.GetObject("security-shield (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap security_shield__1_1 {
            get {
                object obj = ResourceManager.GetObject("security-shield (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show {
            get {
                object obj = ResourceManager.GetObject("show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SignupImage {
            get {
                object obj = ResourceManager.GetObject("SignupImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred! Please try again later!.
        /// </summary>
        internal static string UnknownErrorString {
            get {
                return ResourceManager.GetString("UnknownErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user1 {
            get {
                object obj = ResourceManager.GetObject("user1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be blank!.
        /// </summary>
        internal static string UsernameBlankWarningString {
            get {
                return ResourceManager.GetString("UsernameBlankWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not found! Please try again!.
        /// </summary>
        internal static string UsernameNotFoundWarningString {
            get {
                return ResourceManager.GetString("UsernameNotFoundWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Users {
            get {
                object obj = ResourceManager.GetObject("Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningTitleString {
            get {
                return ResourceManager.GetString("WarningTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrew successfully!.
        /// </summary>
        internal static string WithdrawSuccessfullyString {
            get {
                return ResourceManager.GetString("WithdrawSuccessfullyString", resourceCulture);
            }
        }
    }
}
