// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class CashFlow
{
    public int Id { get; set; }

    public DateTimeOffset Time { get; set; }

    public int CustomerId { get; set; }

    public decimal BalanceChanging { get; set; }

    public string Context { get; set; }

    public virtual CustomerAccount Customer { get; set; }
}