// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class CustomerAccount
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsMale { get; set; }

    public string CicNumber { get; set; }

    public DateOnly BirthDate { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string Username { get; set; }

    public string HashedPassword { get; set; }

    public decimal Balance { get; set; }

    public virtual ICollection<CashFlow> CashFlows { get; set; } = new List<CashFlow>();

    public virtual ICollection<Saving> Savings { get; set; } = new List<Saving>();
}