// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class SavingInterestRate
{
    public byte PeriodInMonths { get; set; }

    public decimal AnnualInterestRate { get; set; }
}