// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class Saving
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public decimal Balance { get; set; }

    public decimal AnnualInterestRate { get; set; }

    public int PeriodInMonths { get; set; }

    public DateTimeOffset OpenDate { get; set; }

    public virtual CustomerAccount Customer { get; set; }
}