// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class StaffAccountType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int PermissionId { get; set; }

    public virtual StaffPermission Permission { get; set; }

    public virtual ICollection<StaffAccount> StaffAccounts { get; set; } = new List<StaffAccount>();
}