// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class StaffPermission
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<StaffAccountType> StaffAccountTypes { get; set; } = new List<StaffAccountType>();
}