// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class StaffAccount
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsMale { get; set; }

    public string Position { get; set; }

    public string Username { get; set; }

    public string HashedPassword { get; set; }

    public int AccountTypeId { get; set; }

    public virtual StaffAccountType AccountType { get; set; }
}